<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Presentation.Shell</AssemblyName>
    <RootNamespace>Presentation.Shell</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="**/tests/**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Presentation.Common.csproj" />
  </ItemGroup>

</Project>
