<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <SourceRoot Condition="'$(SourceRoot)' == ''">$(MSBuildProjectDirectory)\..\build\source</SourceRoot>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="PresentationConsumer.Program.cs" />
    <ProjectReference Include="$(SourceRoot)\core\foundation\Core.Foundation.csproj" />
  </ItemGroup>
</Project>
