<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Presentation.Common</AssemblyName>
    <RootNamespace>Presentation.Common</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="**/tests/**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../core/gameplay/Core.Gameplay.csproj" />
  </ItemGroup>

</Project>
