<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Presentation.FeedbackBinder</AssemblyName>
    <RootNamespace>Presentation.FeedbackBinder</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="**/tests/**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Presentation.Common.csproj" />
    <ProjectReference Include="../vfx_sfx/Presentation.VfxSfx.csproj" />
  </ItemGroup>

</Project>
