<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><Nullable>enable</Nullable></PropertyGroup><ItemGroup><Reference Include="Adapters.Stub"><HintPath>lib\Adapters.Stub.dll</HintPath></Reference><Reference Include="Core.Carriers"><HintPath>lib\Core.Carriers.dll</HintPath></Reference><Reference Include="Core.Foundation"><HintPath>lib\Core.Foundation.dll</HintPath></Reference><Reference Include="Core.Gameplay"><HintPath>lib\Core.Gameplay.dll</HintPath></Reference><Reference Include="Core.Numbers"><HintPath>lib\Core.Numbers.dll</HintPath></Reference><Reference Include="Core.Rules"><HintPath>lib\Core.Rules.dll</HintPath></Reference><Reference Include="Presentation.Common"><HintPath>lib\Presentation.Common.dll</HintPath></Reference></ItemGroup></Project>
